name: reactive_notifier
description: Flutter state management with MVVM-inspired ViewModels & Notifiers. Offers fine-grained control.

version: 2.16.0
homepage: https://github.com/JhonaCodes/reactive_notifier.git
topics:
  - reactive-notifier
  - state-management
  - reactive
  - viewmodel
  - state

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  test: ^1.24.0
  alchemist: ^0.12.1

flutter:
  uses-material-design: true
